apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-deployment
  # template for the pod
  template:
    metadata:
      labels:
        app: react-app-deployment
    # blue prints for container inside pod
    spec:
      containers:
        - image: shrikantsharma606/react-app:v1
          # IfNotPresent Always Never
          imagePullPolicy: Never
          name: react-app-deployment
          ports:
            - containerPort: 80
          env:
            - name: SPRING_BOOT_APP_SERVICE
              valueFrom:
                configMapKeyRef:
                  # name is from secret metada
                  name: app-configmap
                  key: spring-boot-host
